// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-1O3zWg4PJ9SOrC4M8jL8dp3Gb-nfNsc',
    appId: '1:86121734209:web:ced2bbad86bc0683aee6c0',
    messagingSenderId: '86121734209',
    projectId: 'faculty-tracker-30135',
    authDomain: 'faculty-tracker-30135.firebaseapp.com',
    storageBucket: 'faculty-tracker-30135.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtHu-uYfEUsDYSWPEvJO6b2ktIM9ERC4U',
    appId: '1:86121734209:android:151f5e162a4ffd76aee6c0',
    messagingSenderId: '86121734209',
    projectId: 'faculty-tracker-30135',
    storageBucket: 'faculty-tracker-30135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQlDNBrm5Br-BNq8105Mbhp88Zcz1FbNA',
    appId: '1:86121734209:ios:45107dac1afeb51daee6c0',
    messagingSenderId: '86121734209',
    projectId: 'faculty-tracker-30135',
    storageBucket: 'faculty-tracker-30135.firebasestorage.app',
    iosBundleId: 'com.example.facultytracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-1O3zWg4PJ9SOrC4M8jL8dp3Gb-nfNsc',
    appId: '1:86121734209:web:5a00b72dff00d85caee6c0',
    messagingSenderId: '86121734209',
    projectId: 'faculty-tracker-30135',
    authDomain: 'faculty-tracker-30135.firebaseapp.com',
    storageBucket: 'faculty-tracker-30135.firebasestorage.app',
  );
}
